// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAACJeT0fH7zxl-287Bs0n9TZ3SUYpkkDY',
    appId: '1:213746550022:web:2452eef559accc5f534a87',
    messagingSenderId: '213746550022',
    projectId: 'hackmatrix-ba8fb',
    authDomain: 'hackmatrix-ba8fb.firebaseapp.com',
    storageBucket: 'hackmatrix-ba8fb.appspot.com',
    measurementId: 'G-RR6HJM008M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5lkI7HgLpU2lwv-nljEZy0kPtZjRdBE',
    appId: '1:213746550022:android:0c71052a5fe39ec1534a87',
    messagingSenderId: '213746550022',
    projectId: 'hackmatrix-ba8fb',
    storageBucket: 'hackmatrix-ba8fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIC0kxO6vHjVr6NDvatVOjsF-p1g9mdI',
    appId: '1:213746550022:ios:1850cee0dea7559c534a87',
    messagingSenderId: '213746550022',
    projectId: 'hackmatrix-ba8fb',
    storageBucket: 'hackmatrix-ba8fb.appspot.com',
    iosBundleId: 'com.example.projecthack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiIC0kxO6vHjVr6NDvatVOjsF-p1g9mdI',
    appId: '1:213746550022:ios:115a839f83dbb981534a87',
    messagingSenderId: '213746550022',
    projectId: 'hackmatrix-ba8fb',
    storageBucket: 'hackmatrix-ba8fb.appspot.com',
    iosBundleId: 'com.example.projecthack.RunnerTests',
  );
}
